name: Docker Pull

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull docker image
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u token --password-stdin
        docker pull docker.pkg.github.com/jcansdale/gpr/gpr
